allow-branch = ["main"]
consolidate-commits = false
pre-release-commit-message = "chore: bump version to {{version}}"
pre-release-hook = ["sh", "scripts/release-changelog.sh"]
publish = false
push = true
push-remote = "origin"
tag = true
tag-message = "release version v{{version}}"
tag-name = "v{{version}}"
verify = true
